export type EmojiItem = { emoji: string; name: string };
export type EmojiCategory = { name: string; items: EmojiItem[] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Visages",
    items: [
      { emoji: "😊", name: "sourire visage" },
      { emoji: "😄", name: "rire joyeux" },
      { emoji: "😁", name: "grand sourire" },
      { emoji: "🙂", name: "légèrement souriant" },
      { emoji: "😇", name: "halo ange innocent" },
      { emoji: "🥰", name: "amoureux coeur" },
      { emoji: "😍", name: "yeux étoiles amour" },
      { emoji: "🤩", name: "étoiles yeux enthousiaste" },
      { emoji: "🥳", name: "fête chapeau anniversaire" },
      { emoji: "😎", name: "cool lunettes" },
      { emoji: "🧐", name: "monocle curieux" },
      { emoji: "🤔", name: "réfléchir pensif question" },
      { emoji: "🤗", name: "câlin bras ouverts" },
      { emoji: "🤝", name: "poignée de main accord" },
      { emoji: "😌", name: "soulagé calme serein" },
      { emoji: "😔", name: "triste pensif" },
      { emoji: "😢", name: "pleurs larme" },
      { emoji: "😭", name: "sangloter pleurer" },
      { emoji: "😤", name: "frustration vapeur" },
      { emoji: "😡", name: "colère rouge" },
      { emoji: "🥺", name: "suppliant yeux grands" },
      { emoji: "😰", name: "anxieux sueur froide" },
      { emoji: "😨", name: "peur effrayé" },
      { emoji: "😳", name: "gêné rouge honte" },
      { emoji: "🤯", name: "explosion cerveau stupéfait" },
      { emoji: "😷", name: "masque malade grippe" },
      { emoji: "🤒", name: "thermomètre fièvre" },
      { emoji: "🤕", name: "bandage blessé" },
      { emoji: "🥴", name: "étourdi sonnée" },
      { emoji: "😴", name: "dormir sommeil" },
      { emoji: "🤫", name: "chut silence secret" },
      { emoji: "🫡", name: "saluer respect" },
      { emoji: "🫶", name: "coeur mains amour" },
      { emoji: "🫂", name: "câlin étreinte" },
    ],
  },
  {
    name: "Personnes",
    items: [
      { emoji: "👶", name: "bébé nourrisson enfant" },
      { emoji: "🧒", name: "enfant" },
      { emoji: "👦", name: "garçon" },
      { emoji: "👧", name: "fille" },
      { emoji: "🧑", name: "personne adulte" },
      { emoji: "👨", name: "homme" },
      { emoji: "👩", name: "femme" },
      { emoji: "🧓", name: "personnes âgées senior" },
      { emoji: "👴", name: "grand-père ancien" },
      { emoji: "👵", name: "grand-mère ancienne" },
      { emoji: "👨‍⚕️", name: "médecin docteur santé" },
      { emoji: "👩‍⚕️", name: "médecin infirmière santé" },
      { emoji: "👨‍🎓", name: "diplômé étudiant" },
      { emoji: "👩‍🎓", name: "diplômée étudiante" },
      { emoji: "👨‍🏫", name: "enseignant professeur" },
      { emoji: "👩‍🏫", name: "enseignante professeure" },
      { emoji: "👨‍💼", name: "professionnel bureau" },
      { emoji: "👩‍💼", name: "professionnelle bureau" },
      { emoji: "👨‍🍳", name: "cuisinier chef" },
      { emoji: "👩‍🍳", name: "cuisinière chef" },
      { emoji: "🧑‍🤝‍🧑", name: "couple amis ensemble" },
      { emoji: "👨‍👩‍👧", name: "famille parents enfant" },
      { emoji: "👨‍👩‍👧‍👦", name: "famille enfants" },
      { emoji: "👥", name: "groupe personnes communauté" },
      { emoji: "👤", name: "personne silhouette" },
      { emoji: "🧑‍🦯", name: "canne malvoyant" },
      { emoji: "🧑‍🦼", name: "fauteuil roulant handicap" },
    ],
  },
  {
    name: "Santé",
    items: [
      { emoji: "❤️", name: "coeur rouge amour" },
      { emoji: "💙", name: "coeur bleu confiance" },
      { emoji: "💚", name: "coeur vert nature" },
      { emoji: "💜", name: "coeur violet" },
      { emoji: "🧡", name: "coeur orange chaleur" },
      { emoji: "💛", name: "coeur jaune bonheur" },
      { emoji: "🤍", name: "coeur blanc pureté" },
      { emoji: "💕", name: "deux coeurs affection" },
      { emoji: "❤️‍🩹", name: "coeur blessé réparation guérison" },
      { emoji: "❤️‍🔥", name: "coeur feu passion" },
      { emoji: "🧠", name: "cerveau mental intelligence" },
      { emoji: "🫀", name: "coeur anatomique cardio" },
      { emoji: "🫁", name: "poumons respiration" },
      { emoji: "🩺", name: "stéthoscope médecin" },
      { emoji: "💊", name: "médicament pilule traitement" },
      { emoji: "💉", name: "seringue vaccin injection" },
      { emoji: "🩹", name: "pansement soin blessure" },
      { emoji: "🩻", name: "radiographie os examen" },
      { emoji: "🏥", name: "hôpital clinique urgence" },
      { emoji: "🚑", name: "ambulance urgence secours" },
      { emoji: "⚕️", name: "caducée médecine santé" },
      { emoji: "🧬", name: "adn génétique science" },
      { emoji: "🔬", name: "microscope recherche laboratoire" },
      { emoji: "🧪", name: "tube essai expérience" },
      { emoji: "😴", name: "sommeil repos récupération" },
      { emoji: "🧘", name: "méditation yoga bien-être" },
      { emoji: "🧘‍♀️", name: "méditation femme yoga" },
      { emoji: "🧘‍♂️", name: "méditation homme yoga" },
      { emoji: "🏃", name: "courir sport activité" },
      { emoji: "🏋️", name: "musculation force sport" },
      { emoji: "🚴", name: "vélo cyclisme sport" },
      { emoji: "🤸", name: "gym gymnastique souplesse" },
      { emoji: "🏊", name: "nager natation eau" },
      { emoji: "🛌", name: "repos lit dormir" },
      { emoji: "🍏", name: "pomme verte alimentation" },
      { emoji: "🥗", name: "salade légumes nutrition" },
      { emoji: "💆", name: "massage relaxation bien-être" },
      { emoji: "🌿", name: "herbe naturel plante médicinal" },
    ],
  },
  {
    name: "Nature",
    items: [
      { emoji: "🌱", name: "pousse plante croissance" },
      { emoji: "🌿", name: "feuille naturel herbe" },
      { emoji: "🍃", name: "feuilles vent nature" },
      { emoji: "🌾", name: "épi blé céréale" },
      { emoji: "🌵", name: "cactus désert" },
      { emoji: "🌲", name: "arbre forêt pin" },
      { emoji: "🌳", name: "arbre feuillus nature" },
      { emoji: "🌴", name: "palmier tropical" },
      { emoji: "🌺", name: "fleur rouge hibiscus" },
      { emoji: "🌸", name: "fleur cerisier sakura" },
      { emoji: "🌼", name: "fleur jaune marguerite" },
      { emoji: "🌻", name: "tournesol fleur" },
      { emoji: "🌹", name: "rose fleur amour" },
      { emoji: "🌷", name: "tulipe fleur" },
      { emoji: "💐", name: "bouquet fleurs" },
      { emoji: "🍀", name: "trèfle chance" },
      { emoji: "🍁", name: "feuille automne érable" },
      { emoji: "🍂", name: "feuilles tombantes automne" },
      { emoji: "🍄", name: "champignon forêt" },
      { emoji: "🌊", name: "vague océan mer eau" },
      { emoji: "🏔️", name: "montagne sommet" },
      { emoji: "⛰️", name: "montagne nature" },
      { emoji: "🌋", name: "volcan montagne" },
      { emoji: "🏕️", name: "camping tente nature" },
      { emoji: "🌅", name: "lever soleil aurore" },
      { emoji: "🌄", name: "coucher soleil montagne" },
      { emoji: "🌈", name: "arc-en-ciel espoir couleurs" },
      { emoji: "☀️", name: "soleil lumière chaleur" },
      { emoji: "🌙", name: "lune nuit" },
      { emoji: "⭐", name: "étoile brillant" },
      { emoji: "🌟", name: "étoile filante brillant" },
      { emoji: "❄️", name: "neige hiver cristal" },
      { emoji: "🌊", name: "vague eau mer" },
      { emoji: "🦋", name: "papillon transformation liberté" },
      { emoji: "🐝", name: "abeille miel nature" },
      { emoji: "🌍", name: "terre monde planète" },
    ],
  },
  {
    name: "Activités",
    items: [
      { emoji: "🎯", name: "cible objectif but" },
      { emoji: "🎓", name: "diplôme remise apprentissage" },
      { emoji: "📚", name: "livres lecture apprentissage" },
      { emoji: "✏️", name: "crayon écriture" },
      { emoji: "🖊️", name: "stylo écriture" },
      { emoji: "🎨", name: "art peinture créativité" },
      { emoji: "🎭", name: "théâtre masque culture" },
      { emoji: "🎵", name: "musique note son" },
      { emoji: "🎶", name: "musique mélodie notes" },
      { emoji: "🎤", name: "micro chant expression" },
      { emoji: "🎮", name: "jeu vidéo loisir" },
      { emoji: "♟️", name: "échecs stratégie réflexion" },
      { emoji: "🧩", name: "puzzle résoudre logique" },
      { emoji: "⚽", name: "football sport équipe" },
      { emoji: "🏀", name: "basketball sport" },
      { emoji: "🎾", name: "tennis sport raquette" },
      { emoji: "🏊‍♀️", name: "natation nager" },
      { emoji: "🤸‍♀️", name: "gym acrobatie souplesse" },
      { emoji: "⛷️", name: "ski hiver glisse" },
      { emoji: "🚵", name: "vtt vélo montagne" },
      { emoji: "🧗", name: "escalade grimper" },
      { emoji: "🏄", name: "surf vague" },
      { emoji: "🤺", name: "escrime sport" },
      { emoji: "🎲", name: "dés jeu hasard" },
      { emoji: "🎪", name: "cirque spectacle" },
      { emoji: "🎠", name: "manège attraction" },
      { emoji: "🎡", name: "grande roue fête" },
      { emoji: "🛝", name: "toboggan jeu enfants" },
      { emoji: "🤹", name: "jongleur spectacle talent" },
    ],
  },
  {
    name: "Communauté",
    items: [
      { emoji: "🏠", name: "maison foyer domicile" },
      { emoji: "🏡", name: "maison jardin home" },
      { emoji: "🏫", name: "école collège lycée" },
      { emoji: "🏥", name: "hôpital clinique" },
      { emoji: "🏛️", name: "mairie institution bâtiment" },
      { emoji: "⛪", name: "église religion spiritualité" },
      { emoji: "🕌", name: "mosquée islam" },
      { emoji: "🕍", name: "synagogue judaïsme" },
      { emoji: "🕋", name: "kaaba pèlerinage" },
      { emoji: "🛖", name: "cabane refuge abri" },
      { emoji: "🌆", name: "ville urbain" },
      { emoji: "🤝", name: "accord partenariat entraide" },
      { emoji: "🙌", name: "applaudir célébrer ensemble" },
      { emoji: "👐", name: "mains ouvertes accueil" },
      { emoji: "🫶", name: "coeur mains solidarité" },
      { emoji: "🗳️", name: "urne vote démocratie" },
      { emoji: "📢", name: "haut-parleur annonce information" },
      { emoji: "📣", name: "mégaphone appel communication" },
      { emoji: "💬", name: "bulle dialogue discussion" },
      { emoji: "🗣️", name: "parler expression voix" },
      { emoji: "👂", name: "oreille écoute" },
      { emoji: "🔗", name: "lien connexion réseau" },
      { emoji: "🌐", name: "globe internet réseau mondial" },
      { emoji: "🤲", name: "mains offrande aide" },
      { emoji: "💪", name: "bras force pouvoir" },
      { emoji: "✊", name: "poing solidarité résistance" },
      { emoji: "🫱🏼‍🫲🏼", name: "poignée mains alliance" },
    ],
  },
  {
    name: "Apprentissage",
    items: [
      { emoji: "📖", name: "livre ouvert lecture" },
      { emoji: "📝", name: "bloc-notes écriture mémo" },
      { emoji: "📋", name: "presse-papiers liste" },
      { emoji: "📊", name: "graphique statistique données" },
      { emoji: "📈", name: "hausse croissance progrès" },
      { emoji: "💡", name: "ampoule idée inspiration" },
      { emoji: "🔍", name: "loupe recherche investigation" },
      { emoji: "🔎", name: "loupe zoom analyse" },
      { emoji: "🧭", name: "boussole orientation guide" },
      { emoji: "🗺️", name: "carte navigation chemin" },
      { emoji: "🎓", name: "chapeau diplôme formation" },
      { emoji: "🏆", name: "trophée victoire accomplissement" },
      { emoji: "🥇", name: "médaille or premier" },
      { emoji: "⭐", name: "étoile excellence note" },
      { emoji: "🌟", name: "étoile brillante réussite" },
      { emoji: "🎖️", name: "médaille honneur mérite" },
      { emoji: "📌", name: "punaise épingler important" },
      { emoji: "📍", name: "localisation repère" },
      { emoji: "🗂️", name: "dossiers classement organisation" },
      { emoji: "📁", name: "dossier fichier" },
      { emoji: "🖥️", name: "ordinateur écran numérique" },
      { emoji: "💻", name: "laptop portable travail" },
      { emoji: "📱", name: "téléphone mobile smartphone" },
      { emoji: "⌨️", name: "clavier saisie numérique" },
      { emoji: "🖨️", name: "imprimante document" },
      { emoji: "🔑", name: "clé accès solution" },
      { emoji: "🗝️", name: "vieille clé secret mystère" },
      { emoji: "🧲", name: "aimant attraction" },
      { emoji: "⚙️", name: "engrenage mécanique paramètre" },
      { emoji: "🛠️", name: "outils construction réparation" },
    ],
  },
  {
    name: "Symboles",
    items: [
      { emoji: "✅", name: "coché validé accepté" },
      { emoji: "❌", name: "croix refusé interdit" },
      { emoji: "⚠️", name: "attention avertissement danger" },
      { emoji: "ℹ️", name: "information info" },
      { emoji: "❓", name: "question interrogation" },
      { emoji: "❗", name: "exclamation important urgent" },
      { emoji: "💯", name: "cent parfait note" },
      { emoji: "🆕", name: "nouveau récent" },
      { emoji: "🆓", name: "gratuit libre" },
      { emoji: "🔴", name: "rouge cercle" },
      { emoji: "🟠", name: "orange cercle" },
      { emoji: "🟡", name: "jaune cercle" },
      { emoji: "🟢", name: "vert cercle" },
      { emoji: "🔵", name: "bleu cercle" },
      { emoji: "🟣", name: "violet cercle" },
      { emoji: "⚫", name: "noir cercle" },
      { emoji: "⚪", name: "blanc cercle" },
      { emoji: "🔶", name: "orange losange" },
      { emoji: "🔷", name: "bleu losange" },
      { emoji: "♾️", name: "infini éternité" },
      { emoji: "☮️", name: "paix signe" },
      { emoji: "☯️", name: "yin yang équilibre" },
      { emoji: "🕊️", name: "colombe paix liberté" },
      { emoji: "🌀", name: "spirale tourbillon" },
      { emoji: "🔆", name: "luminosité lumière clarté" },
      { emoji: "🔇", name: "silencieux muet" },
      { emoji: "🔔", name: "cloche notification alerte" },
      { emoji: "🔕", name: "cloche silencieuse" },
      { emoji: "📍", name: "épingle localisation" },
      { emoji: "🏷️", name: "étiquette tag label" },
      { emoji: "🎀", name: "ruban noeud cadeau" },
      { emoji: "🎁", name: "cadeau don présent" },
      { emoji: "🌐", name: "globe internet web" },
      { emoji: "🔐", name: "cadenas fermé sécurité" },
      { emoji: "🔓", name: "cadenas ouvert accès" },
      { emoji: "🛡️", name: "bouclier protection sécurité" },
    ],
  },
];
